const Sawikain = [
  { phrase: "Abot-tanaw", definition: "Malapit nang makamit o maabot." },
  { phrase: "Agaw-buhay", definition: "Nasa bingit ng kamatayan." },
  { phrase: "Agaw-dilim", definition: "Oras na palubog na ang araw." },
  { phrase: "Ahas", definition: "Taksil o traydor na tao." },
  { phrase: "Alilang-kanin", definition: "Katulong na pagkain lang ang kapalit." },
  { phrase: "Alog na ang baba", definition: "Matanda na o may edad na." },
  { phrase: "Alsa balutan", definition: "Umalis o naglayas." },
  { phrase: "Amoy pinipig", definition: "Mabango o mahalimuyak." },
  { phrase: "Amoy tsiko", definition: "Lasing o nakainom ng alak." },
  { phrase: "Anak dalita", definition: "Taong salat o mahirap sa buhay." },
  { phrase: "Anak-pawis", definition: "Manggagawa o pangkaraniwang mamamayan." },
  { phrase: "Anghel ng tahanan", definition: "Maliit na bata sa tahanan." },
  { phrase: "Asal hayop", definition: "Masama o bastos ang ugali." },
  { phrase: "Bahag ang buntot", definition: "Duwag o madaling matakot." },
  { phrase: "Bakas ng kahapon", definition: "Alaala o bagay mula sa nakaraan." },
  { phrase: "Balat kalabaw", definition: "Hindi madaling mahiya." },
  { phrase: "Balat-sibuyas", definition: "Sobrang sensitibo o madaling masaktan." },
  { phrase: "Balik-harap", definition: "Mabait sa harap pero taksil sa likod." },
  { phrase: "Balitang kutsero", definition: "Balitang mali o hindi mapagkakatiwalaan." },
  { phrase: "Bantay-salakay", definition: "Tagapagbantay na siya ring nananamantala." },
  { phrase: "Basa ang papel", definition: "Bistado o nahuli na ang lihim." },
  { phrase: "Basag-ulo", definition: "Taong mahilig sa away o gulo." },
  { phrase: "Bilang na ang araw", definition: "Malapit nang mamatay o matapos." },
  { phrase: "Buhok anghel", definition: "Maganda o kaaya-ayang buhok." },
  { phrase: "Bukal sa loob", definition: "Taos-puso at kusang-loob." },
  { phrase: "Bukang liwayway", definition: "Malapit nang mag-umaga." },
  { phrase: "Bukas ang isip", definition: "Handang tumanggap ng opinyon." },
  { phrase: "Bukas na kaban", definition: "Mapagbigay o handang tumulong." },
  { phrase: "Bulaklak ng dila", definition: "Mapang-akit magsalita." },
  { phrase: "Bulaklak ng lipunan", definition: "Babaeng kilala at iginagalang sa lipunan." },
  { phrase: "Bulang-gugo", definition: "Mapagbigay o maluwag sa kapwa." },
  { phrase: "Bumangga sa pader", definition: "Lumaban sa makapangyarihan." },
  { phrase: "Bungang-araw", definition: "Sakit sa balat mula sa init ng araw." },
  { phrase: "Bungang-tulog", definition: "Panaginip o ilusyon lamang." },
  { phrase: "Buntong hininga", definition: "Pagpapahayag ng lungkot o hinagpis." },
  { phrase: "Busilak ang puso", definition: "Mabuti at malinis ang kalooban." },
  { phrase: "Butas ang bulsa", definition: "Walang pera o kapos sa salapi." },
  { phrase: "Buto't balat", definition: "Napakapayat." },
  { phrase: "Buwaya sa katihan", definition: "Nagpapautang nang may malaking tubo." },
  { phrase: "Daga sa dibdib", definition: "Kinakabahan o natatakot." },
  { phrase: "Dalawa ang bibig", definition: "Madaldal o mabunganga." },
  { phrase: "Dalawa ang mukha", definition: "Taksil o doble-kara." },
  { phrase: "Dapit-hapon", definition: "Oras na malapit nang gumabi." },
  { phrase: "Di mahapayang gatang", definition: "Sobrang yabang." },
  { phrase: "Di makabasag-pinggan", definition: "Mahinhin o mahiyain kumilos." },
  { phrase: "Di malaglagang karayom", definition: "Sobrang siksikan o maraming tao." },
  { phrase: "Galit sa pera", definition: "Gastador o madaling gumastos." },
  { phrase: "Ginintuang tinig", definition: "Maganda ang boses." },
  { phrase: "Guhit ng tadhana", definition: "Nakatakdang kapalaran." },
  { phrase: "Halang ang bituka", definition: "Masama o salbahe ang ugali." },
  { phrase: "Halang ang kaluluwa", definition: "Napakasamang tao." },
  { phrase: "Haligi ng tahanan", definition: "Ama o tatay ng pamilya." },
  { phrase: "Hampas ng langit", definition: "Parusa o matinding kaparusahan." },
  { phrase: "Hampas-lupa", definition: "Dukha o napakahirap." },
  { phrase: "Hawak sa leeg", definition: "Sunud-sunuran o kontrolado." },
  { phrase: "Hinahabol ng karayom", definition: "Punit o butas ang damit." },
  { phrase: "Hindi madapuan ng langaw", definition: "Sobrang inaalagaan o pinoprotektahan." },
  { phrase: "Ibaon sa hukay", definition: "Kalimutan nang tuluyan." },
  { phrase: "Ibong mandaragit", definition: "Mananakop o mapagsamantala." },
  { phrase: "Ikrus sa noo", definition: "Tandaan nang mabuti." },
  { phrase: "Ilaw ng tahanan", definition: "Ina o nanay ng pamilya." },
  { phrase: "Isang kahig, isang tuka", definition: "Pamumuhay na kapos at araw-araw ang hanap." },
  { phrase: "Isulat sa tubig", definition: "Kalimutan o huwag nang asahan." },
  { phrase: "Itaga sa bato", definition: "Tandaan o panghawakang tiyak." },
  { phrase: "Itim na tupa", definition: "Masamang anak o miyembro ng pamilya." },
  { phrase: "Kabiyak ng dibdib", definition: "Asawa o minamahal sa buhay." },
  { phrase: "Kakaning-itik", definition: "Walang halaga o hindi kagalang-galang." },
  { phrase: "Kalapating mababa ang lipad", definition: "Babaeng nagbebenta ng aliw." },
  { phrase: "Kamay na bakal", definition: "Mahigpit at malupit na pamamalakad." },
  { phrase: "Kape at gatas", definition: "Magkaibang kulay, maitim at maputi." },
  { phrase: "Kapit tuko", definition: "Mahigpit ang kapit o ayaw bumitaw." },
  { phrase: "Kaututang dila", definition: "Madalas kausap o katsismisan." },
  { phrase: "Kidlat sa bilis", definition: "Napakabilis." },
  { phrase: "Kilos pagong", definition: "Napakabagal kumilos." },
  { phrase: "Kumukulo ang dugo", definition: "Galit na galit o nasusuklam." },
  { phrase: "Kumukulo ang sikmura", definition: "Gutom na gutom." },
  { phrase: "Kusang palo", definition: "Kumikilos nang sariling kusa." },
  { phrase: "Kutsarang ginto sa bibig", definition: "Lumaki sa marangyang buhay." },
  { phrase: "Lahing kuwago", definition: "Gising sa gabi at tulog sa umaga." },
  { phrase: "Lakad pagong", definition: "Mabagal na pagkilos." },
  { phrase: "Laman ng lansangan", definition: "Palaboy o laging nasa kalye." },
  { phrase: "Lamog ang katawan", definition: "Pagod na pagod ang katawan." },
  { phrase: "Lantang gulay", definition: "Matamlay o nanghihina." },
  { phrase: "Lawit ang dila", definition: "Sobrang pagod." },
  { phrase: "Laylay ang balikat", definition: "Bigo o nawalan ng pag-asa." },
  { phrase: "Luha ng buwaya", definition: "Pakitang-taong pag-iyak." },
  { phrase: "Lumagay sa tahimik", definition: "Magpakasal o bumuo ng pamilya." },
  { phrase: "Lumaki ang ulo", definition: "Nagyabang o naging palalo." },
  { phrase: "Lumang tugtugin", definition: "Luma o paulit-ulit nang kuwento." },
  { phrase: "Lumuha man ng bato", definition: "Kahit magsisi, hindi na mapapatawad." },
  { phrase: "Maaliwalas ang mukha", definition: "Masayahin o palangiti." },
  { phrase: "Maamong kordero", definition: "Napakabait o kalmado." },
  { phrase: "Maanghang ang dila", definition: "Masakit o bastos magsalita." },
  { phrase: "Mababa ang loob", definition: "Mapagkumbaba at maawain." },
  { phrase: "Mababaw ang luha", definition: "Madaling umiyak." },
  { phrase: "Mabigat ang dugo", definition: "May sama ng loob o hindi magaan ang pakiramdam sa tao." },
  { phrase: "Mabigat ang kamay", definition: "Tamad kumilos o madaling manakit." },
  { phrase: "Mabigat ang loob", definition: "Nalulungkot o may dinaramdam." },
  { phrase: "Mabilis ang kamay", definition: "Mabilis gumawa o minsan ay mapagnakaw." },
  { phrase: "Madilim ang mukha", definition: "Malungkot o masama ang timpla." },
  { phrase: "Magaan ang dugo", definition: "Madaling pakisamahan." },
  { phrase: "Magaan ang kamay", definition: "Masipag o mabilis tumulong." },
  { phrase: "Magaling ang kamay", definition: "Mahusay gumawa gamit ang kamay." },
  { phrase: "Magdilang-anghel", definition: "Sana ay magkatotoo ang sinabi." },
  { phrase: "Maghalo ang balat sa tinalupan", definition: "Magulo o magkahalo-halo na." },
  { phrase: "Magkataling-puso", definition: "Magkasintahan o magkaugnay sa pag-ibig." },
  { phrase: "Maglaro ng apoy", definition: "Gumawa ng mapanganib na bagay." },
  { phrase: "Maglubid ng buhangin", definition: "Magsinungaling o gumawa ng kuwento." },
  { phrase: "Mahaba ang buntot", definition: "May ginawang kasalanan o kahina-hinala." },
  { phrase: "Mahabang dulang", definition: "Maraming bisita o handaan." },
  { phrase: "Mahangin", definition: "Mayabang." },
  { phrase: "Mahangin ang ulo", definition: "Palalo o mataas ang tingin sa sarili." },
  { phrase: "Mahapdi ang bituka", definition: "Gutom na gutom." },
  { phrase: "Mahina ang loob", definition: "Duwag o madaling panghinaan." },
  { phrase: "Mainit ang ulo", definition: "Madaling magalit." },
  { phrase: "Maitim ang budhi", definition: "Masama ang hangarin." },
  { phrase: "Maitim ang dugo", definition: "Masama o mabigat ang pakiramdam sa kapwa." },
  { phrase: "Makalaglag-matsing", definition: "Nakakagulat o sobrang tindi." },
  { phrase: "Makapal ang bulsa", definition: "Maraming pera." },
  { phrase: "Makapal ang mukha", definition: "Walang hiya." },
  { phrase: "Makapal ang palad", definition: "Masipag." },
  { phrase: "Makati ang dila", definition: "Madaldal o mapuna." },
  { phrase: "Makati ang paa", definition: "Mahilig gumala." },
  { phrase: "Makitid ang isip", definition: "Mahirap umunawa o sarado ang pananaw." },
  { phrase: "Makuskos-balungos", definition: "Mareklamo at mahirap pasayahin." },
  { phrase: "Malakas ang loob", definition: "Matapang at buo ang loob." },
  { phrase: "Malaking isda", definition: "Mayaman o makapangyarihan." },
  { phrase: "Malamig ang ulo", definition: "Kalmado at nasa maayos na kondisyon." },
  { phrase: "Malapad ang papel", definition: "Maraming koneksiyon o kakilala." },
  { phrase: "Malawak ang isip", definition: "Madaling umunawa at bukas ang pananaw." },
  { phrase: "Malikot ang kamay", definition: "Magnanakaw o mapangalikot." },
  { phrase: "Manipis ang mukha", definition: "Mahiyain." },
  { phrase: "Mapait na lunukin", definition: "Mahirap tanggapin na kabiguan." },
  { phrase: "Mapurol ang utak", definition: "Mahina ang pag-iisip." },
  { phrase: "Maputi ang tainga", definition: "Kuripot." },
  { phrase: "Masama ang loob", definition: "May tampo o sama ng loob." },
  { phrase: "Masama ang panahon", definition: "May paparating na malakas na ulan o bagyo." },
  { phrase: "Matalas ang dila", definition: "Masakit magsalita." },
  { phrase: "Matalas ang mata", definition: "Madaling makakita o makapansin." },
  { phrase: "Matalas ang tainga", definition: "Mabilis makarinig ng balita." },
  { phrase: "Matalas ang ulo", definition: "Matalino." },
  { phrase: "Matamis ang dila", definition: "Mahusay mangumbinsi o mambola." },
  { phrase: "Matandang kalabaw", definition: "Matandang tao." },
  { phrase: "Matigas ang buto", definition: "Malakas ang katawan." },
  { phrase: "Matigas ang katawan", definition: "Tamad." },
  { phrase: "Matigas ang leeg", definition: "Mayabang o mapagmataas." },
  { phrase: "Matigas ang ulo", definition: "Ayaw makinig o sumunod." },
  { phrase: "May ipot sa ulo", definition: "Pinagtaksilan ng asawa." },
  { phrase: "May krus ang dila", definition: "Parang natutupad ang sinasabi." },
  { phrase: "May magandang hinaharap", definition: "May mabuting kinabukasan." },
  { phrase: "May sinasabi", definition: "Mayaman o may natatanging kakayahan." },
  { phrase: "Nag-aapoy sa init", definition: "Napakataas ng lagnat." },
  { phrase: "Nagbabatak ng buto", definition: "Nagtatrabaho nang mabigat." },
  { phrase: "Nagbibilang ng poste", definition: "Walang trabaho at naghahanap ng mapapasukan." },
  { phrase: "Nagbukas ng dibdib", definition: "Nagtapat ng hangaring magpakasal." },
  { phrase: "Nagmumurang kamatis", definition: "Matandang nag-aastang bata." },
  { phrase: "Nagpupusa", definition: "Nagkukuwento tungkol sa ibang tao." },
  { phrase: "Nagsaulian ng kandila", definition: "Nag-away o hindi nagkasundo." },
  { phrase: "Nagsusunog ng kilay", definition: "Masipag mag-aral." },
  { phrase: "Nakahiga sa salapi", definition: "Napakayaman." },
  { phrase: "Nakapinid ang tainga", definition: "Nagbibingi-bingihan." },
  { phrase: "Namamangka sa dalawang ilog", definition: "May dalawang karelasyon o pagtataksil." },
  { phrase: "Namuti ang mata", definition: "Nainip sa matagal na paghihintay." },
  { phrase: "Naniningalang-pugad", definition: "Nanliligaw." },
  { phrase: "Natuka ng ahas", definition: "Napatulala o hindi makapagsalita." },
  { phrase: "Ningas-kugon", definition: "Magaling lang sa simula." },
  { phrase: "Pag-iisang dibdib", definition: "Kasal." },
  { phrase: "Pagkagat ng dilim", definition: "Paglubog ng araw o simula ng gabi." },
  { phrase: "Pagputi ng uwak", definition: "Imposibleng mangyari." },
  { phrase: "Panakip butas", definition: "Pansamantalang kapalit." },
  { phrase: "Panis ang laway", definition: "Tahimik o hindi palakibo." },
  { phrase: "Pantay ang mga paa", definition: "Patay na." },
  { phrase: "Parang aso't pusa", definition: "Laging nag-aaway." },
  { phrase: "Parang kiti-kiti", definition: "Malikot at hindi mapakali." },
  { phrase: "Parehong kaliwa ang paa", definition: "Hindi marunong sumayaw." },
  { phrase: "Patabaing baboy", definition: "Palamunin o tamad." },
  { phrase: "Patay-gutom", definition: "Matakaw o laging gutom." },
  { phrase: "Pinagbubuhatan ng kamay", definition: "Pinapalo o sinasaktan." },
  { phrase: "Pulot-gata", definition: "Honeymoon ng bagong kasal." },
  { phrase: "Pusong mamon", definition: "Madaling maawa o malambot ang puso." },
  { phrase: "Pusong-bakal", definition: "Matigas ang damdamin at hindi mapagpatawad." },
  { phrase: "Putok sa buho", definition: "Anak sa labas." },
  { phrase: "Saling-pusa", definition: "Nakikisali lamang." },
  { phrase: "Samaing palad", definition: "Malas na tao." },
  { phrase: "Sampay-bakod", definition: "Peke o hindi mapagkakatiwalaan." },
  { phrase: "Sampid-bakod", definition: "Nakikitira o nakikisama lamang." },
  { phrase: "Sanga-sangang dila", definition: "Sinungaling." },
  { phrase: "Sariling pugad", definition: "Sariling tahanan." },
  { phrase: "Sariwa sa alaala", definition: "Hindi pa nalilimutan." },
  { phrase: "Sira ang tuktok", definition: "Loko-loko o hindi matino." },
  { phrase: "Sukat ang bulsa", definition: "Marunong humawak ng pera." },
  { phrase: "Takaw-tulog", definition: "Mahilig matulog." },
  { phrase: "Talusaling", definition: "Madaling masaktan." },
  { phrase: "Talusira", definition: "Hindi tumutupad sa pangako." },
  { phrase: "Tatlo ang mata", definition: "Mapaghanap ng mali." },
  { phrase: "Tawang-aso", definition: "Nangmamaliit o nagyayabang." },
  { phrase: "Tengang kawali", definition: "Nagbibingi-bingihan." },
  { phrase: "Tinik sa lalamunan", definition: "Hadlang sa layunin." },
  { phrase: "Tulak ng bibig", definition: "Salita lang at hindi bukal sa loob." },
  { phrase: "Umaalon ang dibdib", definition: "Kinakabahan." },
  { phrase: "Utak-biya", definition: "Mahina ang pang-unawa." },
  { phrase: "Utang na loob", definition: "Malaking pasasalamat na dapat tumanawin." },
  { phrase: "Walang bahid", definition: "Malinis o walang kasalanan." },
];

export function normalizeSawikain(phrase) {
  return phrase.toUpperCase().replace(/[^A-Z]/g, "");
}

const unique = [...new Map(Sawikain.map(item => [normalizeSawikain(item.phrase), item])).values()];

export default unique.map(item => ({
  ...item,
  letters: normalizeSawikain(item.phrase),
}));
