const Sawikain = [
  "Anghel ng tahanan",
  "Bahag ang buntot",
  "Balitang kutsero",
  "Bukang liwayway",
  "Bulaklak ng dila",
  "Bumangga sa pader",
  "Busilak ang puso",
  "Buntong hininga",
  "Butas ang bulsa",
  "Buwaya sa katihan",
  "Ilaw ng tahanan",
  "Haligi ng tahanan",
  "Bantay-salakay",
  "Balat sibuyas",
  "Panakip-butas",
  "Pusong bakal",
  "Taingang kawali",
  "Siling labuyo",
  "Pasang krus",
  "Pakitang tao",
  "Ningas-kugon",
  "Bulang-gugo",
  "Bungang-tulog",
  "Nagmumurang kamyas",
  "Putok sa buho",
  "Pinitpit na luya",
  "Kinahig ng manok",
  "Sanga-sangang dila",
  "Dilang anghel",
  "Halang ang bituka",
  "Anak-pawis",
  "Basa ang papel",
  "Basag-ulo",
  "Basang sisiw",
  "Daga sa dibdib",
  "Dalawa ang bibig",
  "Dalawa ang mukha",
  "Dapit-hapon",
  "Di mahapayang gatang",
  "Di makabasag-pinggan",
  "Di malaglagang karayom",
  "Galit sa pera",
  "Ginintuang tinig",
  "Guhit ng tadhana",
  "Halang ang kaluluwa",
  "Hampas ng langit",
  "Hampas-lupa",
  "Hawak sa leeg",
  "Hinahabol ng karayom",
  "Hindi madapuan ng langaw",
  "Ibaon sa hukay",
  "Ibong mandaragit",
  "Ikrus sa noo",
  "Isang bulate na lang ang hindi pumipirma",
  "Isang kahig, isang tuka",
  "Isulat sa tubig",
  "Itaga sa bato",
  "Itim na tupa",
  "Kabiyak ng dibdib",
  "Kakaning-itik",
  "Kalapating mababa ang lipad",
  "Kamay na bakal",
  "Kape at gatas",
  "Kapit tuko",
  "Kaututang dila",
  "Kidlat sa bilis",
  "Kilos pagong",
  "Kumukulo ang dugo",
  "Kumukulo ang sikmura",
  "Kusang palo",
  "Kutsarang ginto sa bibig",
  "Lahing kuwago",
  "Lakad pagong",
  "Laman ng lansangan",
  "Lamog ang katawan",
  "Lantang gulay",
  "Lawit ang dila",
  "Laylay ang balikat",
  "Luha ng buwaya",
  "Lumagay sa tahimik",
  "Lumaki ang ulo",
  "Lumang tugtugin",
  "Lumuha man ng bato",
  "Maaliwalas ang mukha",
  "Maamong kordero",
  "Maanghang ang dila",
  "Mababa ang loob",
  "Mababaw ang luha",
  "Mabigat ang dugo",
  "Mabigat ang kamay",
  "Mabigat ang loob",
  "Mabilis ang kamay",
  "Madilim ang mukha",
  "Magaan ang dugo",
  "Magaan ang kamay",
  "Magaling ang kamay",
  "Magdilang-anghel",
  "Maghalo ang balat sa tinalupan",
  "Magkataling-puso",
  "Maglaro ng apoy",
  "Maglubid ng buhangin",
  "Mahaba ang buntot",
  "Mahabang dulang",
  "Mahangin",
  "Mahangin ang ulo",
  "Mahapdi ang bituka",
  "Mahina ang loob",
  "Mainit ang ulo",
  "Maitim ang budhi",
  "Maitim ang dugo",
  "Makalaglag-matsing",
  "Makapal ang bulsa",
  "Makapal ang mukha",
  "Makapal ang palad",
  "Makati ang dila",
  "Makati ang paa",
  "Makitid ang isip",
  "Makuskos-balungos",
  "Malakas ang loob",
  "Malaking isda",
  "Malamig ang ulo",
  "Malapad ang papel",
  "Malawak ang isip",
  "Malikot ang kamay",
  "Manipis ang mukha",
  "Mapait na lunukin",
  "Mapurol ang utak",
  "Maputi ang tainga",
  "Masama ang loob",
  "Masama ang panahon",
  "Matalas ang dila",
  "Matalas ang mata",
  "Matalas ang tainga",
  "Matalas ang ulo",
  "Matamis ang dila",
  "Matandang kalabaw",
  "Matigas ang buto",
  "Matigas ang katawan",
  "Matigas ang leeg",
  "Matigas ang ulo",
  "May ipot sa ulo",
  "May krus ang dila",
  "May magandang hinaharap",
  "May sinasabi",
  "Nag-aapoy sa init",
  "Nagbabatak ng buto",
  "Nagbibilang ng poste",
  "Nagbukas ng dibdib",
  "Nagmumurang kamatis",
  "Nagpupusa",
  "Nagsaulian ng kandila",
  "Nagsusunog ng kilay",
  "Nakahiga sa salapi",
  "Nakapinid ang tainga",
  "Namamangka sa dalawang ilog",
  "Namuti ang mata",
  "Naniningalang-pugad",
  "Natuka ng ahas",
  "Pag-iisang dibdib",
  "Pagkagat ng dilim",
  "Pagputi ng uwak",
  "Panakip butas",
  "Panis ang laway",
  "Pantay ang mga paa",
  "Parang aso't pusa",
  "Parang kiti-kiti",
  "Parehong kaliwa ang paa",
  "Patabaing baboy",
  "Patay-gutom",
  "Pinagbubuhatan ng kamay",
  "Pulot-gata",
  "Pusong mamon",
  "Pusong-bakal",
  "Saling-pusa",
  "Samaing palad",
  "Sampay-bakod",
  "Sampid-bakod",
  "Sariling pugad",
  "Sariwa sa alaala",
  "Sira ang tuktok",
  "Sukat ang bulsa",
  "Takaw-tulog",
  "Talusaling",
  "Talusira",
  "Tatlo ang mata",
  "Tawang-aso",
  "Tengang kawali",
  "Tinik sa lalamunan",
  "Tulak ng bibig",
  "Umaalon ang dibdib",
  "Utak-biya",
  "Utang na loob",
];

export function normalizeSawikain(phrase) {
  return phrase.toUpperCase().replace(/[^A-Z]/g, "");
}

const unique = [...new Map(Sawikain.map(phrase => [normalizeSawikain(phrase), phrase])).values()];

export default unique.map(phrase => ({
  phrase,
  letters: normalizeSawikain(phrase),
}));
