const Sawikain = [
  { phrase: "Abot-tanaw", definition: "Malapit nang makamit o maabot." },
  { phrase: "Agaw-buhay", definition: "Nasa bingit ng kamatayan." },
  { phrase: "Agaw-dilim", definition: "Oras na palubog na ang araw." },
  { phrase: "Ahas", definition: "Taksil o traydor na tao." },
  { phrase: "Alilang-kanin", definition: "Katulong na pagkain lang ang kapalit." },
  { phrase: "Alog na ang baba", definition: "Matanda na o may edad na." },
  { phrase: "Alsa balutan", definition: "Umalis o naglayas." },
  { phrase: "Amoy pinipig", definition: "Mabango o mahalimuyak." },
  { phrase: "Amoy tsiko", definition: "Lasing o nakainom ng alak." },
  { phrase: "Anak dalita", definition: "Taong salat o mahirap sa buhay." },
  { phrase: "Anak-pawis", definition: "Manggagawa o pangkaraniwang mamamayan." },
  { phrase: "Anghel ng tahanan", definition: "Maliit na bata sa tahanan." },
  { phrase: "Asal hayop", definition: "Masama o bastos ang ugali." },
  { phrase: "Bahag ang buntot", definition: "Duwag." },
  { phrase: "Bakas ng kahapon", definition: "Alaala o bagay mula sa nakaraan." },
  { phrase: "Balat kalabaw", definition: "Hindi madaling mahiya." },
  { phrase: "Balat-sibuyas", definition: "Maramdamin; Sobrang sensitibo." },
  { phrase: "Balik-harap", definition: "Mabait sa harap pero taksil sa likod." },
  { phrase: "Balitang kutsero", definition: "Maling balita." },
  { phrase: "Bantay-salakay", definition: "Hindi mapagkakatiwalaan." },
  { phrase: "Basa ang papel", definition: "Bistado o nahuli na ang lihim." },
  { phrase: "Basag-ulo", definition: "Taong mahilig sa away o gulo." },
  { phrase: "Buhok anghel", definition: "Maganda o kaaya-ayang buhok." },
  { phrase: "Bukal sa loob", definition: "Taos-puso at kusang-loob." },
  { phrase: "Bukang liwayway", definition: "Malapit nang mag-umaga." },
  { phrase: "Bukas ang isip", definition: "Handang tumanggap ng opinyon." },
  { phrase: "Bukas na kaban", definition: "Mapagbigay o handang tumulong." },
  { phrase: "Bulaklak ng dila", definition: "Nakaeengganyo ng ibang tao, totoo man o hindi ang sinasabi." },
  { phrase: "Bulang-gugo", definition: "Mapagbigay; Maluwag sa kapwa." },
  { phrase: "Bumangga sa pader", definition: "Lumaban sa mayaman." },
  { phrase: "Bungang-araw", definition: "Sakit sa balat mula sa init ng araw." },
  { phrase: "Bungang-tulog", definition: "Panaginip; Pangarap." },
  { phrase: "Buntong hininga", definition: "Paghihimutok." },
  { phrase: "Busilak ang puso", definition: "Kabutihang loob." },
  { phrase: "Butas ang bulsa", definition: "Walang pera." },
  { phrase: "Buwaya sa katihan", definition: "Nagpapautang nang malaki ang tubo." },
  { phrase: "Daga sa dibdib", definition: "Kinakabahan o natatakot." },
  { phrase: "Dalawa ang bibig", definition: "Madaldal o mabunganga." },
  { phrase: "Dalawa ang mukha", definition: "Taksil o doble-kara." },
  { phrase: "Dapit-hapon", definition: "Oras na malapit nang gumabi." },
  { phrase: "Galit sa pera", definition: "Gastador o madaling gumastos." },
  { phrase: "Guhit ng tadhana", definition: "Nakatakdang kapalaran." },
  { phrase: "Haligi ng tahanan", definition: "Ama." },
  { phrase: "Hampas ng langit", definition: "Parusa o matinding kaparusahan." },
  { phrase: "Hampas-lupa", definition: "Dukha o napakahirap." },
  { phrase: "Hawak sa leeg", definition: "Sunud-sunuran o kontrolado." },
  { phrase: "Ibaon sa hukay", definition: "Kalimutan nang tuluyan." },
  { phrase: "Ikrus sa noo", definition: "Tandaan nang mabuti." },
  { phrase: "Ilaw ng tahanan", definition: "Ina." },
  { phrase: "Isulat sa tubig", definition: "Kalimutan o huwag nang asahan." },
  { phrase: "Itaga sa bato", definition: "Tandaan o panghawakang tiyak." },
  { phrase: "Itim na tupa", definition: "Masamang anak o miyembro ng pamilya." },
  { phrase: "Kakaning-itik", definition: "Walang halaga o hindi kagalang-galang." },
  { phrase: "Kamay na bakal", definition: "Mahigpit at malupit na pamamalakad." },
  { phrase: "Kape at gatas", definition: "Magkaibang kulay, maitim at maputi." },
  { phrase: "Kapit tuko", definition: "Mahigpit ang kapit o ayaw bumitaw." },
  { phrase: "Kaututang dila", definition: "Madalas kausap o katsismisan." },
  { phrase: "Kidlat sa bilis", definition: "Napakabilis." },
  { phrase: "Kilos pagong", definition: "Napakabagal kumilos." },
  { phrase: "Kusang palo", definition: "Kumikilos nang sariling kusa." },
  { phrase: "Lahing kuwago", definition: "Gising sa gabi at tulog sa umaga." },
  { phrase: "Lakad pagong", definition: "Mabagal na pagkilos." },
  { phrase: "Lantang gulay", definition: "Matamlay o nanghihina." },
  { phrase: "Lawit ang dila", definition: "Sobrang pagod." },
  { phrase: "Luha ng buwaya", definition: "Pakitang-taong pag-iyak." },
  { phrase: "Lumaki ang ulo", definition: "Nagyabang o naging palalo." },
  { phrase: "Lumang tugtugin", definition: "Luma o paulit-ulit nang kuwento." },
  { phrase: "Maamong kordero", definition: "Napakabait o kalmado." },
  { phrase: "Mababa ang loob", definition: "Mapagkumbaba at maawain." },
  { phrase: "Mababaw ang luha", definition: "Madaling umiyak." },
  { phrase: "Mabigat ang dugo", definition: "May sama ng loob o hindi magaan ang pakiramdam sa tao." },
  { phrase: "Mabigat ang loob", definition: "Nalulungkot o may dinaramdam." },
  { phrase: "Magaan ang dugo", definition: "Madaling pakisamahan." },
  { phrase: "Magaan ang kamay", definition: "Masipag o mabilis tumulong." },
  { phrase: "Maglaro ng apoy", definition: "Gumawa ng mapanganib na bagay." },
  { phrase: "Mahabang dulang", definition: "Maraming bisita o handaan." },
  { phrase: "Mahangin", definition: "Mayabang." },
  { phrase: "Mahangin ang ulo", definition: "Palalo o mataas ang tingin sa sarili." },
  { phrase: "Mahina ang loob", definition: "Duwag o madaling panghinaan." },
  { phrase: "Mainit ang ulo", definition: "Madaling magalit." },
  { phrase: "Maitim ang budhi", definition: "Masama ang hangarin." },
  { phrase: "Maitim ang dugo", definition: "Masama o mabigat ang pakiramdam sa kapwa." },
  { phrase: "Makati ang dila", definition: "Madaldal o mapuna." },
  { phrase: "Makati ang paa", definition: "Mahilig gumala." },
  { phrase: "Makitid ang isip", definition: "Mahirap umunawa o sarado ang pananaw." },
  { phrase: "Malakas ang loob", definition: "Matapang at buo ang loob." },
  { phrase: "Malaking isda", definition: "Mayaman o makapangyarihan." },
  { phrase: "Malamig ang ulo", definition: "Kalmado at nasa maayos na kondisyon." },
  { phrase: "Malawak ang isip", definition: "Madaling umunawa at bukas ang pananaw." },
  { phrase: "Mapurol ang utak", definition: "Mahina ang pag-iisip." },
  { phrase: "Masama ang loob", definition: "May tampo o sama ng loob." },
  { phrase: "Matalas ang dila", definition: "Masakit magsalita." },
  { phrase: "Matalas ang mata", definition: "Madaling makakita o makapansin." },
  { phrase: "Matalas ang ulo", definition: "Matalino." },
  { phrase: "Matamis ang dila", definition: "Mahusay mangumbinsi o mambola." },
  { phrase: "Matigas ang buto", definition: "Malakas ang katawan." },
  { phrase: "Matigas ang leeg", definition: "Mayabang o mapagmataas." },
  { phrase: "Matigas ang ulo", definition: "Ayaw makinig o sumunod." },
  { phrase: "May ipot sa ulo", definition: "Pinagtaksilan ng asawa." },
  { phrase: "May krus ang dila", definition: "Parang natutupad ang sinasabi." },
  { phrase: "May sinasabi", definition: "Mayaman o may natatanging kakayahan." },
  { phrase: "Nag-aapoy sa init", definition: "Napakataas ng lagnat." },
  { phrase: "Nagmumurang kamyas", definition: "Matandang nag-aastang bata." },
  { phrase: "Nagpupusa", definition: "Nagkukuwento tungkol sa ibang tao." },
  { phrase: "Namuti ang mata", definition: "Nainip sa matagal na paghihintay." },
  { phrase: "Ningas-kugon", definition: "Sa una lang magaling." },
  { phrase: "Pagputi ng uwak", definition: "Imposibleng mangyari." },
  { phrase: "Pakitang tao", definition: "Pakitang-mahal; Ginagawa para sa palabas lamang." },
  { phrase: "Panakip butas", definition: "Panghalili; Pamalit." },
  { phrase: "Panis ang laway", definition: "Tahimik o hindi palakibo." },
  { phrase: "Pasang krus", definition: "Tinitiis ang hirap o pasanin sa buhay." },
  { phrase: "Patabaing baboy", definition: "Palamunin o tamad." },
  { phrase: "Patay-gutom", definition: "Matakaw o laging gutom." },
  { phrase: "Pulot-gata", definition: "Honeymoon ng bagong kasal." },
  { phrase: "Pusong mamon", definition: "Madaling maawa o malambot ang puso." },
  { phrase: "Pusong-bakal", definition: "Hindi marunong magpatawad." },
  { phrase: "Putok sa buho", definition: "Anak sa labas." },
  { phrase: "Saling-pusa", definition: "Nakikisali lamang." },
  { phrase: "Samaing palad", definition: "Malas na tao." },
  { phrase: "Sampay-bakod", definition: "Peke o hindi mapagkakatiwalaan." },
  { phrase: "Sampid-bakod", definition: "Nakikitira o nakikisama lamang." },
  { phrase: "Sariling pugad", definition: "Sariling tahanan." },
  { phrase: "Sariwa sa alaala", definition: "Hindi pa nalilimutan." },
  { phrase: "Sira ang tuktok", definition: "Loko-loko o hindi matino." },
  { phrase: "Sukat ang bulsa", definition: "Marunong humawak ng pera." },
  { phrase: "Takaw-tulog", definition: "Mahilig matulog." },
  { phrase: "Talusaling", definition: "Madaling masaktan." },
  { phrase: "Talusira", definition: "Hindi tumutupad sa pangako." },
  { phrase: "Tatlo ang mata", definition: "Mapaghanap ng mali." },
  { phrase: "Tawang-aso", definition: "Nangmamaliit o nagyayabang." },
  { phrase: "Tengang kawali", definition: "Nagbibingi-bingihan." },
  { phrase: "Tulak ng bibig", definition: "Salita lang at hindi bukal sa loob." },
  { phrase: "Utak-biya", definition: "Mahina ang pang-unawa." },
  { phrase: "Utang na loob", definition: "Malaking pasasalamat na dapat tumanawin." },
  { phrase: "Walang bahid", definition: "Malinis o walang kasalanan." },
];

export function normalizeSawikain(phrase) {
  return phrase.toUpperCase().replace(/[^A-Z]/g, "");
}

const unique = [...new Map(Sawikain.map(item => [normalizeSawikain(item.phrase), item])).values()];

export default unique.map(item => ({
  ...item,
  letters: normalizeSawikain(item.phrase),
}));
